// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahuwcoocemayyphdrmjz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFodXdjb29jZW1heXlwaGRybWp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MDQ4NzIsImV4cCI6MjA2NjI4MDg3Mn0.vE-fSJMD91TZicpK6eLyHZi7tprfh4hVi_wjRolj_2w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});